### PR TITLE
[feature]: get rid of `npm`/`yarn` commands

### LINKED ISSUE #10: [Feature Request]: Cache fetched `engines` data
### Describe your request

Right now, `depngn` fetches the `engines` data of all dependencies on every execution. This isn't terrible to wait for once, but if I want to rapidly see what support is for several versions of Node in a row, the wait can be tedious.

It would be nice if we could cache the fetched values so subsequent executions are faster.

### Possible Implementation

I know we can cache things inside `node_modules` (it has a hidden `.cache` directory). The spec for this directory isn't standardized yet, but I know [AVA](https://github.com/avajs/ava) and [nyc](https://github.com/istanbuljs/nyc) are working on it, and this library -- [`find-cache-dir`](https://github.com/sindresorhus/find-cache-dir) -- might help.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #13: [Feature Request]: Fetch engine data with `npm` libraries instead of using `exec`
### Describe your request

Right now, a handful of internal functions are implemented using Node's `exec` function (it allows us to execute terminal commands programmatically). For some of them, this doesn't matter much, because it's only one command (for example,  `npm ls`, which just  lists dependencies).

However, there is one instance where we can probably optimize -- fetching engines data. As currently implemented, we create an array of "promisified" `exec` calls of `npm view {DEP_NAME}@${DEP_VERSION} engines --json` -- one for each dependency -- and then use `await promise.all`.

I'm proposing that we get rid of this use of `exec` and attempt to fetch the data directly from the `npm` registry so we only have to make one fetch call.

### Possible Implementation

The current implementation looks like this (where the variables in the string template are the package manager-specific command (`npm view`), the dependency name and the dependency version):

```ts
// src/queries/getEngines.ts

const depsArray = Object.keys(deps).map(async (dep) => {
  const engines = await asyncExec(
    `${manager.engines} ${dep}@${deps[dep].version} engines --json`
  );
  const range = parseEngines(engines, manager);
  return {
    package: dep,
    range,
  };
});
```

Under the hood, `npm view` uses some external `npm` libraries to fetch from the `npm` registry. We can: 
- look into the source code of that particular `npm` command (https://github.com/npm/cli/blob/latest/lib/commands/view.js)
- figure out how they are fetching the data
- do it ourselves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kindoflew**
This PR removes the use of ~`npm view`~ `npm`/`yarn` commands in favor of reading from `package-lock.json` or `node_modules` directly.

Closes #10 and closes #13 by making them irrelevant.

# Context

The biggest bottleneck in the app right now is the amount of time it takes to run `npm view` for all dependencies. Originally, I was considering using whatever package `npm` uses under the hood in the `view` command to try and optimize, but I realized recently that all of the information we need *should* actually be in the repo it's being run in. This led me to look into just reading the info from file instead of fetching. The execution time difference is wild:

- with `npm view`: ~2s (and this is with a good internet connection on a fast computer)
- reading from filesystem: ~330ms (😱)

(ran these rough benchmarks with `npm` and `yarn` on projects with few dependencies and times were pretty consistent for both -- basically takes less than 1/4 the time of the original implementation)

With this bottleneck out of the way, it opens up a lot more flexibility in how we implement other features, because we can worry a *little* less about performance. It also makes testing easier because we won't have to mock out `fetch` calls to `npm` (plus, tests will run way faster).

# Changes
(**EDIT**: see comment below for additional changes)

- removed `npm view` calls
- replaced them with package manager-specific functions that read the info from the filesystem. `package-lock.json` for `npm` and `node_modules` for `yarn` (by finding `node_modules/{PACKAGE_NAME}/packge.json`)
- added some type info for `package.json` and `package-lock.json`
- renamed `PACKAGE_MANAGER` to `MANAGERS` because I didn't like how it looked 😅 
- added `lockFile: string` to `Manager` objects

I don't believe this would be a breaking change -- it'd just improve performance by a lot.

# QA
- inside the `cli` function (`src/cli/index.ts`), wrap `execWithLog` and `createReport` with `console.time` calls
- switch back and forth between this branch and `main`, running `npm run dev` in each
- compare times
- also, all tests should pass and stuff should work how it's supposed to

```typescript
console.time('depngn');
const compatData = await execWithLog(
  'Fetching engine data',
  async () => await depngn({ version, cwd })
);
await createReport(compatData, version, reporter);
console.timeEnd('depngn');
```

### CODE REVIEW

**Comment by kindoflew** [comment]
# Update

I refactored a few more things and reduced execution time even further to ~20ms.

# New Changes
(TL;DR -- stop using all `npm`/`yarn` commands and just read everything from `package.json`, `package-lock.json`, and `node_modules`)

- `getDependencies` now also reads from file (`package.json`) instead of executing `npm ls`
- `getDependencies` now returns an array of strings (package names) instead of an object (we no longer need to know the exact version number of each package because we aren't using `npm view`. also, slightly more performant because we don't have to reduce to new objects, we just filter out unwanted package names)
- removed `list` from `Manager` objects
- renamed `queries` directory to `depngn` (they aren't really queries anymore because we aren't fetching anything. subjective change, but i like it more)
- moved `depngn` function definition to `depngn/index.ts` and then re-export it from `src/index.ts` (also subjective, but i think this is a better format and matches the `cli` directory now)
- added `readJsonFile` helper to `utils`
- added `tslib` dev dependency so we can use spread arrays in function parameters (because of `readJsonFile` helper). you might have to regenerate `node_modules` because an old version of `tslib` is included as an optional dependency of one of the `rollup` plugins

**Comment by kindoflew** [comment]
# Also

I have a PR ready that has unit tests for all of `depngn` directory and most of `cli` directory. It's based on this PR though, so I'll open when this is merged. (https://github.com/kindoflew/depngn/tree/feature/proper-tests)

**Comment by KostiantynPopovych** [comment]
Hey @kindoflew, what about naming the current `depngn` folder as `core`? Naming it `depngn` inside the `src` sounds a bit confusing to me.
The rest looks good to me!

**Comment by kindoflew** [comment]
@KostiantynPopovych ooohh, i like that a lot more. good call!

**Comment by kindoflew** [comment]
@KostiantynPopovych i made the update to the directory name and merged changes from `main`!

**Comment by KostiantynPopovych** [comment]
@kindoflew, during the review, I found the new interface for `package.json`, and now I recall that it may contain the `resolutions` field. So, shouldn't we take care of that field as well? But if yes, it might be better to have it as the standalone feature, and not to include in the current PR (?)

**Comment by kindoflew** [comment]
@KostiantynPopovych -- good call! i added a handful more fields that I got from https://docs.npmjs.com/cli/v9/configuring-npm/package-json, plus `resolutions` (which is `yarn` specific)

**Comment by KostiantynPopovych** [comment]
@kindoflew Looks good, thank you!

**Pull request merged**
